# Generated by Django 4.1.7 on 2023-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('copies_sold', models.IntegerField()),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
