# Generated by Django 4.1.7 on 2023-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('nationality', models.CharField(max_length=200)),
                ('books_sold', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
    ]
