# Generated by Django 4.1.7 on 2023-03-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0003_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('headquarter', models.CharField(max_length=200)),
                ('established', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('total_copies_sold', models.IntegerField()),
            ],
        ),
    ]
