# Generated by Django 4.1.7 on 2023-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0006_publishedbooks_publisher_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedbooks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
