# Generated by Django 4.1.7 on 2023-03-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0007_alter_publishedbooks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Lab_1.book'),
        ),
        migrations.AlterField(
            model_name='publishedbooks',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='Lab_1.publisher'),
        ),
    ]
