# Generated by Django 4.1.7 on 2023-03-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0008_alter_publishedbooks_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishedBooks', to='Lab_1.book'),
        ),
    ]
