# Generated by Django 4.1.7 on 2023-04-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0011_alter_author_books_sold_alter_book_copies_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='desciption',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
