# Generated by Django 4.1.7 on 2023-04-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0013_rename_desciption_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
