# Generated by Django 4.1.7 on 2023-04-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0016_registrationconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='RegistrationConfirmation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
