# Generated by Django 4.1.7 on 2023-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_1', '0019_remove_userprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='2002-09-09'),
            preserve_default=False,
        ),
    ]
